apiVersion: v1
kind: Service
metadata:
  name: pgclient
spec:
  type: ClusterIP
  selector:
    app: pgclient
  ports:
  - name: http
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgclient
spec:
  selector:
    matchLabels:
      app: pgclient
  replicas: 1
  template:
    metadata:
      labels:
        app: pgclient
    spec:
      containers:
      - name: main
        image: gcr.io/mokeefe/pgclient:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      # - name: cloudsql-proxy
      #   image: gcr.io/cloudsql-docker/gce-proxy:1.14
      #   command: ["/cloud_sql_proxy",
      #             "-instances=<INSTANCE_CONNECTION_NAME>=tcp:3306",

      #             "-credential_file=/secrets/cloudsql/credentials.json"]
      #   securityContext:
      #     runAsUser: 2  # non-root user
      #     allowPrivilegeEscalation: false
      #   volumeMounts:
      #     - name: cloudsql-instance-credentials
      #       mountPath: /secrets/cloudsql
      #       readOnly: true