apiVersion: "rbac.istio.io/v1alpha1"
kind: ClusterRbacConfig
metadata:
  name: default
spec:
  mode: 'ON_WITH_INCLUSION'
  inclusion:
    namespaces: ["default"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: render-viewer
  namespace: default
spec:
  rules:
  - services: ["render.default.svc.cluster.local"]
    methods: ["GET", "HEAD"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: binding-render-viewer
  namespace: default
spec:
  subjects:
  - properties:
      request.headers[hello]: "megan"
  roleRef:
    kind: ServiceRole
    name: "render-viewer"